### PR TITLE
QA : Format & Lint

### LINKED ISSUE #135: QA : Need of code linter and Formatter
- Need a workflow that ensures every contributor should follow the [PEP-8](https://www.python.org/dev/peps/pep-0008/) style guide for python code.
- We can use `flake8` for linting and `Black` for formatting source code.
- Also this workflow runs on every PR which ensures the code follows  [PEP-8](https://www.python.org/dev/peps/pep-0008/) standard or not.

### PR DESCRIPTION
**Pull request by Aryamanz29**
# Description

Closes #135

- Integrate [Black](https://pypi.org/project/black/) and [Flake8](https://pypi.org/project/flake8/) for format & linting of source code
- Added workflow `.github/workflows/qa_checks.yml` and script `lifeMEDeasy_QA_checks` , Which ensures contributor follow [PEP8](https://www.python.org/dev/peps/pep-0008/) standard for python.
- Update `README.md` with `how to run` instructions.

### TEST:
- Tested on Github actions, See build below👇
**Success Build:** https://github.com/Aryamanz29/lifeMEDeasy/actions/runs/852322917

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by Aryamanz29** [comment]
@chetan-rns  @avinashkranjan  Please review this PR

**Comment by chetan-rns** [comment]
@Aryamanz29 Could you please add `"parser": "babel-eslint"` to `eslintrc.json`. This should fix the lint checks in the CI. Apart from that everything looks good to me

**Review by chetan-rns — APPROVED** [review]

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Could you please add `"parser": "babel-eslint"` to `eslintrc.json`. This should fix the lint checks in the CI. Apart from that everything looks good to me

Sure ✌

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Could you please add `"parser": "babel-eslint"` to `eslintrc.json`. This should fix the lint checks in the CI. Apart from that everything looks good to me

Please check recent commit

**Comment by Aryamanz29** [comment]
@chetan-rns  Why checks Failing?

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
