### PR TITLE
Fixed position of Navbar

### PR DESCRIPTION
**Pull request by Saatvik21**
# Description

I've made the navbar sticky/fixed on all the pages so that the user should not have to scroll up again and again to go to different pages on the website.

## Related Issues or Pull Requests

Fixes: #149
 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by Saatvik21** [comment]
@chetan-rns @Aasthajain123 @avinashkranjan Please review my PR

**Comment by chetan-rns** [comment]
Thanks @Saatvik21 LGTM!

**Comment by chetan-rns** [comment]
Seems like `npm run lint` is failing because of missing `"parser": "babel-eslint"` in `.eslintrc.json`

**Review by chetan-rns — APPROVED** [review]

**Comment by Saatvik21** [comment]
> Seems like `npm run lint` is failing because of missing `"parser": "babel-eslint"` in `.eslintrc.json`

Can you elaborate what should I do now?

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
