### PR TITLE
Forget password page and login page

### PR DESCRIPTION
**Pull request by kumarishalini6**
#123
I have made a forget password page and modified login page.
React App - Personal - Microsoft​ Edge 4_19_2021 02_06_37 PM
React App - Personal - Microsoft​ Edge 4_19_2021 02_07_10 PM

React App - Personal - Microsoft​ Edge 4_19_2021 02_06_10 PM

### CODE REVIEW

**Comment by avinashkranjan** [comment]
Hey @kumarishalini6 Don't Change the Color Theme

**Comment by kumarishalini6** [comment]
Sorry ,I'll change the image

**Comment by kumarishalini6** [comment]
React App - Personal - Microsoft​ Edge 4_23_2021 02_22_38 PM
React App - Personal - Microsoft​ Edge 4_23_2021 02_22_10 PM

**Comment by kumarishalini6** [comment]
is this ok for forgot password
React App - Personal - Microsoft​ Edge 4_26_2021 06_56_03 PM

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Add a SignIn/SignUp Button on the nav bar, Resolve the conflicts

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
i have tried but this issue is not resolved
MINGW64__c_Users_Asus_desktop_lifeMEDeasy 5_2_2021 07_25_17 PM

**Comment by kumarishalini6** [comment]
done

**Comment by kumarishalini6** [comment]
Hey! i have remove the conflicts but don't know know about workflow error

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
