### PR TITLE
Improvement for covid section

### PR DESCRIPTION
**Pull request by Dhriti-Roy**
# Description

Added new Section for Covid Patients in Navigation bar as well as on home screen.Added Registration page for covid patients. I also made some changes and updated the code.

#(Mention Issue Number Here.)
Issue no. - #115 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by chetan-rns** [comment]
Hi @Dhriti-Roy, there's already a PR #108 that solves a similar problem. How is this different?

**Comment by chetan-rns** [comment]
Commit messages should give a context of changes being made :) Please check https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

**Comment by dhritiduttroy** [comment]
Thanks for suggesting me that article on commit messages , I will sure keep that in mind next time .

**Comment by dhritiduttroy** [comment]
Well , mine is different because I have linked a registeration form which is going to open when the user selects the "covid patients" option. Whereas, in #108 she has added the function for covid testing. "Registeration form for covid patients " and "testing for covid" are two different things. Thus, my PR is different.

**Comment by Dhriti-Roy** [comment]
> Commit messages should give a context of changes being made :) Please check https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

Thanks for suggesting me this article. I will surely keep this in my mind next time, while making the PR.

**Comment by Dhriti-Roy** [comment]
> Hi @Dhriti-Roy, there's already a PR #108 that solves a similar problem. How is this different?

Mine is different, because in #108 she has added the form for "testing of covid" and here, I have added the form for "registration of covid patients" , and I guess both are quite different.

**Comment by Dhriti-Roy** [comment]
> Hi @Dhriti-Roy, there's already a PR #108 that solves a similar problem. How is this different?

Hey, she has added the covid-section in navigation bar, same as I have done but I have also added the covid section on home screen, form where they can register. 

If there is any need then I can remove my code for navigation bar, thus both the code will not contradict each other.
And you can add my code for "Registration of Covid Patients"' on home screen.

**Pull request closed without merging**
