### PR TITLE
Adding hover effect on navbar

### PR DESCRIPTION
**Pull request by kumarishalini6**
#109
I have added hover effect in navbar

https://user-images.githubusercontent.com/69043944/114294760-26db5600-9a4d-11eb-8dd6-fb275611a78e.mp4

https://user-images.githubusercontent.com/69043944/114295005-dbc24280-9a4e-11eb-8d51-485f78020182.mp4

### CODE REVIEW

**Comment by avinashkranjan** [comment]
@kumarishalini6 Resolve the conflicts

**Comment by kumarishalini6** [comment]
Hey! i have solve the conflicts file but don't know about workflow error

**Comment by kumarishalini6** [comment]
Not able to switch on this branch

**Comment by avinashkranjan** [comment]
> Not able to switch on this branch

You might have deleted the branch..

**Comment by chetan-rns** [comment]
@kumarishalini6 Please fix the merge conflicts

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
Done

**Pull request merged**
