### PR TITLE
Fix issue #197 Diabetes Prediction

### PR DESCRIPTION
**Pull request by Dishita2602**
# Description

Data Set - https://www.kaggle.com/uciml/pima-indians-diabetes-database

Have performed data preprocessing and data visualizations

Training 80% and Testing 20%

**Applied Classifier Machine learning Models -** Random Forest ( Random SearchCV ), Decision Tree, Naive Bayes

Best Results obtained by Random Forest 81.18%

## Related Issues or Pull Requests

fixes #164 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by Dishita2602** [comment]
@Aasthajain123 I this you should re-label this issue.. 
I feel I have done enough work so this issue at least deserve more than level 1

**Comment by chetan-rns** [comment]
@Dishita2602 Could you please add more details to the PR? 
1. Description for the change (what/why/how)
2. Link the issue which the PR is trying to fix

**Comment by Dishita2602** [comment]
> @Dishita2602 Could you please add more details to the PR?
> 
> 1. Description for the change (what/why/how)
> 2. Link the issue which the PR is trying to fix

Done . Pleases review it.

**Comment by chetan-rns** [comment]
@Dishita2602 Is this integrated with the website? Do you think we need to add documentation for this so folks can understand how to use this? In OpenSource documentation holds the same precedence as code :)

**Comment by Dishita2602** [comment]
> @Dishita2602 Is this integrated with the website? Do you think we need to add documentation for this so folks can understand how to use this? In OpenSource documentation holds the same precedence as code :)

Absolutely yes we can integrate it with website as I have attached pkl regarding same. No I don't think any documentation is required I have explained all important point in comment for better understanding

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
Kindly Create a Corresponding Issue and Move the files in `ML-Models` folder

**Comment by Dishita2602** [comment]
> Kindly Create a Corresponding Issue and Move the files in `ML-Models` folder
By which name do I need to create corresponding issue. Can you please be more specific ?

**Comment by Dishita2602** [comment]
> > Kindly Create a Corresponding Issue and Move the files in `ML-Models` folder
> > By which name do I need to create corresponding issue. Can you please be more specific ?



> > Kindly Create a Corresponding Issue and Move the files in `ML-Models` folder
> 
> By which name do I need to create corresponding issue. Can you please be more specific ?
> Secondly if you wanted this changes then why you guys are mentioning correction one by one. During this pandemic it's difficult to make correction one after other. I have too many responsibilities. I hope you are understanding what I am trying to say..
> Thank you !!

@avinashkranjan @chetan-rns @Aasthajain123

**Comment by avinashkranjan** [comment]
> > Kindly Create a Corresponding Issue and Move the files in `ML-Models` folder
> 
> By which name do I need to create corresponding issue. Can you please be more specific ?
> Secondly if you wanted this changes then why you guys are mentioning correction one by one. During this pandemic it's difficult to make correction one after other. I have too many responsibilities. I hope you are understanding what I am trying to say..
> Thank you !!

Hey @Dishita2602, Create an Issue for which you have create a PR. For documentation purposes..Everyone is busy handling their personal and professional life in this pandemic...When the Project Mentors are free then only they'll review the PR..and suggest the changes...No One's asking to make the changes as soon as it's asked..take your time...But PR review would be happen this way only..Kindly consider that

**Comment by Dishita2602** [comment]
> > > Kindly Create a Corresponding Issue and Move the files in `ML-Models` folder
> > 
> > 
> > By which name do I need to create corresponding issue. Can you please be more specific ?
> > Secondly if you wanted this changes then why you guys are mentioning correction one by one. During this pandemic it's difficult to make correction one after other. I have too many responsibilities. I hope you are understanding what I am trying to say..
> > Thank you !!
> 
> Hey @Dishita2602, Create an Issue for which you have create a PR. For documentation purposes..Everyone is busy handling their personal and professional life in this pandemic...When the Project Mentors are free then only they'll review the PR..and suggest the changes...No One's asking to make the changes as soon as it's asked..take your time...But PR review would be happen this way only..Kindly consider that

I have created an issue please have a look at it.

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
