### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by kumarishalini6**
#112
I have made dark mod for the project

### CODE REVIEW

**Comment by avinashkranjan** [comment]
@kumarishalini6 Kindly Add SS of changes Made

**Comment by kumarishalini6** [comment]
ya sure

**Comment by kumarishalini6** [comment]
React App - Personal - Microsoft​ Edge 4_17_2021 04_18_03 PM
React App - Personal - Microsoft​ Edge 4_17_2021 04_18_41 PM
React App - Personal - Microsoft​ Edge 4_17_2021 04_19_06 PM

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
@kumarishalini6 Kindly Move the Slider of Dark & Light Mode.. To Navbar

**Comment by kumarishalini6** [comment]
ok i'll do that please give me some time i have MST on my head

**Comment by kumarishalini6** [comment]
done 
React App - Personal - Microsoft​ Edge 5_14_2021 03_48_43 PM

**Comment by kumarishalini6** [comment]
please review this PR

**Comment by kumarishalini6** [comment]
Please review this also

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
