### PR TITLE
bugs in project

### PR DESCRIPTION
**Pull request by kumarishalini6**
#179 

I have removed all the bugs present in the project like:--
the login card was 2 times in the same page, buttons  were different in different cards, some links were not visible

### CODE REVIEW

**Comment by chetan-rns** [comment]
@kumarishalini6  Navigating to the emergency page is throwing an error. Steps to reproduce
1. Start the server npm start and go to the main page
2. Click on the emergency button on the navbar

**Comment by kumarishalini6** [comment]
Ya the error is because of hook file , I guess that was important that's why I didn't do anything on that

**Comment by kumarishalini6** [comment]
@chetan-rns  suggest me what to do , should i delete that file ?

**Comment by kumarishalini6** [comment]
and Doctor , Patients links are also not working

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Pull request merged**
